### ISSUE TITLE
Implementation of intersection_*_print functionality

### ISSUE THREAD

**Issue by You-Ay** [You-Ay/vectors#12]
The `intersect_*` routines calculate possible intersections between objects and store the relevant information in one of the `intersection_*` data structures. For testing (and solving math homework), it is practical or even essential to have a facility to print the intersection information easily to screen. This should be done by the routines
```C
void intersection_pointlike_print(const intersection_pointlike *intersection);
void intersection_linelike_print(const intersection_linelike *intersection);
void intersection_circular_print(const intersection_circular *intersection);
```
Example outputs for a point like intersection could be (or similar):
`Parallel, no intersection.\n`
`Skew, no intersection.\n`
`Intersection at (1.000, 0.000, -5.000), ray parameter r = 2.500.\n`
`Two intersections at (-1.000, 0.000, 1.000) and (1.000, 0.000, 1.000).\n`
(and so on)

**Comment by Const-He** [comment]
Regarding ray_sphere_intersections:

The intersection datatype doesn't specify which two objects intersect, meaning that the program can't differentiate between intersections with initialized and unititialized r_2 and P_2. Trying to access these variables in the case that they are unitialized (eg to print the second intersection or to check them for a specific value) leads to undefined behaviour, AFAIK.
Correct me, if I'm wrong.

**Comment by You-Ay** [comment]
You are right, feel free to add more fine-grained function declarations to the header file, e.g.:

```C
void intersection_print_ray_ray(const intersection *I, int places);
void intersection_print_ray_plane(const intersection *I, int places);
void intersection_print_ray_sphere(const intersection *I, int places);
```
