### ISSUE TITLE
Implementation of absorption law

### ISSUE THREAD

**Issue by You-Ay** [You-Ay/vectors#14]
Whenever a ray hits an object, a part of its color may be absorbed by the object. For example, when a grey ray with RGB color (0.5, 0.5, 0.5) hits a red object, with RGB color (1, 0, 0), the ray looses its green and blue components. After the interaction, the color changes to (0.5, 0, 0). Mathematically, this is a component-wise multiplication of the colors, schematically

`New red = old red * object's red`
`New green = old green * object's green`
`New blue = old blue * object's blue`

Remember that all object data structures have a `color col;` instance, which is just a vector. The red part of a ray pointer *g is thus `g->col.x` etc..

Apart from the color, the ray is not modified by absorption! Ray origin and direction are changed according to the subsequent interaction (scattering, reflection, refraction).

The function declaration is in `optics.h`:

```C
// a ray is partially absorbed or illuminated:
// the ray color is multiplied by the object's color;
// - for a black absorber, this would be (0, 0, 0) erasing all color,
// - for a red surface, (1, 0, 0) would absorb everything but red,
// - for a light source, e.g. (10, 10, 10) would illumate
void absorb(ray *g, color col);
```

**Comment by MBachelet** [comment]
How do you differentiate between the initial color vector and the new? 
Initially, I wanted to commit the following:

void absorb(ray *g, color col);
	g->col.x = colour_col.x * g->col.x
	g->col.y = colour_col.y * g->col.y
	g->col.z = colour_col.z * g->col.z
}

But isn't it a problem that both the old and new vector are called "g->col.x/y/z" ?

**Comment by You-Ay** [comment]
That's no problem because the `=` operator in C is not a mathematical equal sign. In fact, the program just calculates what's on the right-hand side and just afterwards stores it in the variable on the left. There is no conflict after all.

Still, you access the values of `col` by `col.x`, `col.y` and `col.z`. So, the first line should read
```C
g->col.x = col.x * g->col.x;
```
Or you use the `*=` operator,
```C
g->col.x *= col.x;
```
which does the same.
