### ISSUE TITLE
Implementation of reflection law

### ISSUE THREAD

**Issue by You-Ay** [You-Ay/vectors#15]
When a ray hits a mirror-like surface, it is reflected. As explained in [https://en.wikipedia.org/wiki/Specular_reflection](url):

"The law of reflection states that for each incident ray the angle of incidence equals the angle of reflection, and the incident, normal, and reflected directions are coplanar."

You will also find a vector formulation of this law in the same article.

The reflection law has to be implemented in `optics.c` as the routine `reflect(ray *g, vector normal, point P)` taking as input the original ray (that has to be modified), the normal vector to the surface, and the interaction point `P`.

Pay attention to the fact the normal vector to the surface may point in two different directions and that it is not necessarily normalized by default.

```C
// mirror materials:
// reflect according to the law of reflection of classical optics,
// cf. en.wikipedia.org/wiki/Specular_reflection
void reflect(ray *g, vector normal, point P);
```

**Comment by Const-He** [comment]
The reflect function seems to work independently of the normal vector's orientation.

**Comment by You-Ay** [comment]
True!

However, the ray direction was assumed outgoing from the surface. In our code, the ray "moves" from smaller ray parameter r to larger ray parameter r, it will thus have the opposite orientation when hitting the surface. (Corrected in last commit.)

**Comment by MBachelet** [comment]
Does udirection stand for the initial direction vector?

**Comment by Const-He** [comment]
udirection is the unit vector corresponding to the initial direction vector. In order to obtain the correct outgoing direction, you have to use unit vectors.

**Comment by MBachelet** [comment]
Ok, now I understand, thank you!
