### ISSUE TITLE
Implementation of triangles and rectangles in objects.c

### ISSUE THREAD

**Issue by MBachelet** [You-Ay/vectors#20]

**Comment by Const-He** [comment]
In order to render more complex surfaces, it is necessary to have finite surfaces (i.e. triangles and rectangles).

**Comment by MBachelet** [comment]
It could be useful to add circles and cylinders.

**Comment by Const-He** [comment]
What still needs to be done:

Modify the geogebra and gnuplot print functions to support triangles and parallelograms. (if possible)

circles and cylinders should be treated in a different issue.

**Comment by You-Ay** [comment]
GeoGebra and Gnuplot support is added and works.
