### ISSUE TITLE
Implementation of "real time rendering" option

### ISSUE THREAD

**Issue by MBachelet** [You-Ay/vectors#22]
It might be useful to add a possibility to output each rendered sample immediately (and not after the 
program has rendered all images) and a command to end the rendering without loosing all the calculations
(the output would be the lastest image rendered).
This could especially be useful while creating a scenery in order to monitor the results as quickly as possible, not really to render a final picture (it will take more time).

**Comment by You-Ay** [comment]
This is implemented in the `render_live` routine: There is no fixed number of samples; the renderer runs indefinitely and writes the results into the image file after each step.
